# Site settings
title: Gruesso Labs
email: info@gruessolabs.com
description: Welcome to Gruesso Labs
baseurl: "gruessolabs.com" # the subpath of your site, e.g. /blog/
url: "gruessolabs.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
